version: "3.9"
services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes"
  
  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    ports:
      - "6380:6379"
    command: >
      sh -c "redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes"
  
  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    ports:
      - "6381:6379"
    command: >
      sh -c "redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes"
